# This workflow is used to create the Cloud3dPrint_Control_Panel_app_<env>.zip package and upload to s3.

name: Control_Panel_Package_Upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ awsTest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create the control package
        run: |
          echo Creating Control Panel Package
          mkdir control
          rsync -rv --exclude=.git --exclude=.keep --exclude=control --exclude=.github . control
          ls control
          echo Control Panel Folder created
      
      - name: Zip the package
        run: |
          echo Zipping the package
          zip -r control.zip control
          mv control.zip Cloud3dPrint_Control_Panel_App_test.zip  
          echo Zip Package created
          ls
          echo
          echo
          pwd
          
      - name: Push to S3
        run: |
          echo Uploading Package to s3
          result=$(curl --location --request POST '99.79.10.183:7005/cloudStorage/api/uploadFileForUrl' \
          --form 'fileName="Cloud3DPrint_Control_Panel_App_test"' \
          --form 'fileType="controlPanel"' \
          --form 'fileExtension="zip"' \
          --form 'file=@"/home/runner/work/GithubActionsTest/GithubActionsTest/Cloud3dPrint_Control_Panel_App_test.zip"')
          echo $result
          
